# Generated by Django 4.2.2 on 2024-10-31 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('max_number_of_persons', models.IntegerField()),
                ('hotel_type', models.CharField(max_length=50)),
                ('food_type', models.CharField(max_length=50)),
                ('number_of_days', models.IntegerField()),
                ('number_of_nights', models.IntegerField()),
                ('visiting_places', models.TextField()),
                ('description', models.TextField()),
                ('tour_date', models.DateField()),
                ('is_approved', models.BooleanField(default=False)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('vendor', 'Vendor'), ('user', 'User')], max_length=10)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
